version: '3'

services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres_host
    volumes:
      - db-data:/var/lib/postgresql/data
     # - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    restart: always
    build: ./web
    container_name: web_content
    expose:
      - "8000"
    #links:
    #  - postgres:postgres
    depends_on:
      - postgres
    volumes:
      - web-data:/flask_app/app/static
      - upload-files:/upload_folder
    env_file: 
      - .env
    #command: /usr/local/bin/gunicorn -w 2 --bind 0.0.0.0:8000 wsgi

  nginx:
    restart: always
    build: ./nginx
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - web-data:/flask_app/app/static
    #links:
    #  - web:web
    depends_on:
      - web

  data:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    #depends_on:
    #  - postgres
    #command: "true"

volumes:
  db-data:
  web-data:
  upload-files:
